CREATE OR REPLACE DATABASE DB_LAB;
CREATE OR REPLACE SCHEMA CHAT_APP;
CREATE OR REPLACE TABLE CONVERSATIONS (
    CONVERSATION_ID STRING,
    TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ROLE STRING,
    CONTENT STRING
);